### ISSUE TITLE
Server doesn't accept RSA SHA-2 keys.

### ISSUE THREAD

**Issue by thepixelmonk** [quackduck/devzat#77] opened 2022-03-16 08:27 UTC
I'm getting a permission denied error even though I have a public key generated. Any ideas?

```
λ ssh pixelmonk@devzat.hackclub.com
pixelmonk@devzat.hackclub.com: Permission denied (publickey).

λ ls ~/.ssh
id_rsa  id_rsa.pub  known_hosts  known_hosts.old
```

**Comment by Arkaeriit** [comment] 2022-03-16 08:49
This is mentioned in the Readme, you should use the command `ssh-keygen` to get a public key and be able to log in.

Alternatively, you can log to the port 443 which doesn't require a public key.

**Comment by thepixelmonk** [comment] 2022-03-16 08:51
> This is mentioned in the Readme, you should use the command `ssh-keygen` to get a public key and be able to log in.

Like I said, I already have a public key, which you can see above. Am I missing something?

**Comment by thepixelmonk** [comment] 2022-03-16 09:00
Found a hacker news post which I think is relevant. It just doesn't like RSA. https://news.ycombinator.com/item?id=30690988

**Comment by quackduck** [comment] 2022-03-19 02:42
Yeah this is a known issue with some crypto libs: see https://github.com/golang/crypto/pull/197 , https://github.com/gliderlabs/ssh/issues/145 & https://github.com/charmbracelet/soft-serve/issues/48

**Comment by quackduck** [comment] 2022-03-22 02:27
This problem hasn't been solved, reopening.

**Comment by kuquay** [comment] 2022-03-23 00:53
Not sure if this is a related error, but I've also been unable to log on to the server, although only recently, as of the beginning of this week. My error is `Unable to negotiate with 150.136.142.44 port 22: no matching host key type found. Their offer: ssh-rsa`
Generating new keys of both RSA and ED25519 variety does not work, as the server does not offer a (working) host key.

**Comment by quackduck** [comment] 2022-03-23 01:06
Did you get the same error as @thepixelmonk before this week? I wonder if simply changing the server’s ssh key would fix this.

**Comment by kuquay** [comment] 2022-03-23 01:37
@quackduck I got no errors before this week.

**Comment by quackduck** [comment] 2022-03-23 02:24
changing the server key will have all old user clients complaining about a possible man in the middle attack lol

**Comment by kuquay** [comment] 2022-03-23 02:26
@quackduck If no one can reproduce the issue, it's probably not worth it, I don't want to cause all those issues just because I maybe have something on my end.

**Comment by quackduck** [comment] 2022-03-23 04:14
No this is a legitimate issue a lot of people face: I have to tell them to use port 443. 

We're mostly waiting on the libs here to add support: https://github.com/quackduck/devzat/issues/77#issuecomment-1072923781

**Comment by kuquay** [comment] 2022-03-23 05:01
For the record, I fixed it by restarting. The RSA SHA-2 issue is unrelated.
I should add that when I had that issue, Port 443 did not work.

**Comment by quackduck** [comment] 2022-03-23 22:25
Hey @thepixelmonk could you run `ssh -v devzat.hackclub.com` and let me know what it says?

**Comment by thepixelmonk** [comment] 2022-03-27 06:13
```
λ ssh -v devzat.hackclub.com
OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to devzat.hackclub.com [150.136.142.44] port 22.
debug1: Connection established.
debug1: identity file /c/Users/Chris/.ssh/id_rsa type 0
debug1: identity file /c/Users/Chris/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/Chris/.ssh/id_dsa type -1
debug1: identity file /c/Users/Chris/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/Chris/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/Chris/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/Chris/.ssh/id_ecdsa_sk type -1
debug1: identity file /c/Users/Chris/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /c/Users/Chris/.ssh/id_ed25519 type 3
debug1: identity file /c/Users/Chris/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/Chris/.ssh/id_ed25519_sk type -1
debug1: identity file /c/Users/Chris/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /c/Users/Chris/.ssh/id_xmss type -1
debug1: identity file /c/Users/Chris/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.8
debug1: Remote protocol version 2.0, remote software version Go
debug1: compat_banner: no match: Go
debug1: Authenticating to devzat.hackclub.com:22 as 'Chris'
debug1: load_hostkeys: fopen /c/Users/Chris/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: (no match)
Unable to negotiate with 150.136.142.44 port 22: no matching host key type found. Their offer: ssh-rsa

~/.ssh
λ ls
id_ed25519  id_ed25519.pub  id_rsa  id_rsa.pub  known_hosts  known_hosts.old
```

**Comment by quackduck** [comment] 2022-03-27 06:22
For comparison, this is mine:
```
[~]  ssh -v devzat.hackclub.com
OpenSSH_8.6p1, LibreSSL 2.8.3
debug1: Reading configuration data /Users/ishan/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to devzat.hackclub.com port 22.
debug1: Connection established.
debug1: identity file /Users/ishan/.ssh/id_rsa type 0
debug1: identity file /Users/ishan/.ssh/id_rsa-cert type -1
debug1: identity file /Users/ishan/.ssh/id_dsa type -1
debug1: identity file /Users/ishan/.ssh/id_dsa-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519 type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/ishan/.ssh/id_xmss type -1
debug1: identity file /Users/ishan/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.6
debug1: Remote protocol version 2.0, remote software version Go
debug1: compat_banner: no match: Go
debug1: Authenticating to devzat.hackclub.com:22 as 'ishan'
debug1: load_hostkeys: fopen /Users/ishan/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
```

**Comment by quackduck** [comment] 2022-03-27 06:31
After updating openssh I get the same issue:
```
OpenSSH_8.9p1, OpenSSL 1.1.1n  15 Mar 2022
debug1: Reading configuration data /Users/ishan/.ssh/config
debug1: Reading configuration data /opt/homebrew/etc/ssh/ssh_config
debug1: Connecting to devzat.hackclub.com [150.136.142.44] port 22.
debug1: Connection established.
debug1: identity file /Users/ishan/.ssh/id_rsa type 0
debug1: identity file /Users/ishan/.ssh/id_rsa-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519 type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/ishan/.ssh/id_xmss type -1
debug1: identity file /Users/ishan/.ssh/id_xmss-cert type -1
debug1: identity file /Users/ishan/.ssh/id_dsa type -1
debug1: identity file /Users/ishan/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9
debug1: Remote protocol version 2.0, remote software version Go
debug1: compat_banner: no match: Go
debug1: Authenticating to devzat.hackclub.com:22 as 'ishan'
debug1: load_hostkeys: fopen /Users/ishan/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /opt/homebrew/etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /opt/homebrew/etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: (no match)
Unable to negotiate with 150.136.142.44 port 22: no matching host key type found. Their offer: ssh-rsa
```

**Comment by quackduck** [comment] 2022-03-27 06:36
We could solve this by using a third-party fork of `x/crypto` but that isn't optimal:

https://github.com/replicatedhq/kots/pull/2613/files

**Comment by quackduck** [comment] 2022-03-27 06:39
Okay here's a tracking issue for this problem: https://github.com/golang/go/issues/49952

**Comment by quackduck** [comment] 2022-03-29 01:47
I update some dependencies and the verbose messages have now changed. It appears it goes a bit further this time:

```
OpenSSH_8.9p1, OpenSSL 1.1.1n  15 Mar 2022
debug1: Reading configuration data /Users/ishan/.ssh/config
debug1: Reading configuration data /opt/homebrew/etc/ssh/ssh_config
debug1: Connecting to devzat.hackclub.com [150.136.142.44] port 22.
debug1: Connection established.
debug1: identity file /Users/ishan/.ssh/id_rsa type 0
debug1: identity file /Users/ishan/.ssh/id_rsa-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/ishan/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519 type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/ishan/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/ishan/.ssh/id_xmss type -1
debug1: identity file /Users/ishan/.ssh/id_xmss-cert type -1
debug1: identity file /Users/ishan/.ssh/id_dsa type -1
debug1: identity file /Users/ishan/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9
debug1: Remote protocol version 2.0, remote software version Go
debug1: compat_banner: no match: Go
debug1: Authenticating to devzat.hackclub.com:22 as 'ishan'
debug1: load_hostkeys: fopen /Users/ishan/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /opt/homebrew/etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /opt/homebrew/etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-rsa SHA256:0NFbqn9ACSQBVVjvqcVsGl0vtVUq9n//nJgEwB25UFk
debug1: load_hostkeys: fopen /Users/ishan/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /opt/homebrew/etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /opt/homebrew/etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'devzat.hackclub.com' is known and matches the RSA host key.
debug1: Found key in /Users/ishan/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
debug1: Will attempt key: /Users/ishan/.ssh/id_rsa RSA SHA256:/30Vhs3sufvZ/NTJVIUiSTwpFyvDEh10bIOyiZO9cj4
debug1: Will attempt key: /Users/ishan/.ssh/id_ecdsa
debug1: Will attempt key: /Users/ishan/.ssh/id_ecdsa_sk
debug1: Will attempt key: /Users/ishan/.ssh/id_ed25519
debug1: Will attempt key: /Users/ishan/.ssh/id_ed25519_sk
debug1: Will attempt key: /Users/ishan/.ssh/id_xmss
debug1: Will attempt key: /Users/ishan/.ssh/id_dsa
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/ishan/.ssh/id_rsa RSA SHA256:/30Vhs3sufvZ/NTJVIUiSTwpFyvDEh10bIOyiZO9cj4
debug1: send_pubkey_test: no mutual signature algorithm
debug1: Trying private key: /Users/ishan/.ssh/id_ecdsa
debug1: Trying private key: /Users/ishan/.ssh/id_ecdsa_sk
debug1: Trying private key: /Users/ishan/.ssh/id_ed25519
debug1: Trying private key: /Users/ishan/.ssh/id_ed25519_sk
debug1: Trying private key: /Users/ishan/.ssh/id_xmss
debug1: Trying private key: /Users/ishan/.ssh/id_dsa
debug1: No more authentication methods to try.
ishan@devzat.hackclub.com: Permission denied (publickey).
```

Diff:
```diff
29,31c29,66
< debug1: kex: algorithm: curve25519-sha256@libssh.org
< debug1: kex: host key algorithm: (no match)
< Unable to negotiate with 150.136.142.44 port 22: no matching host key type found. Their offer: ssh-rsa
\ No newline at end of file
---
> debug1: kex: algorithm: curve25519-sha256
> debug1: kex: host key algorithm: rsa-sha2-512
> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
> debug1: SSH2_MSG_KEX_ECDH_REPLY received
> debug1: Server host key: ssh-rsa SHA256:0NFbqn9ACSQBVVjvqcVsGl0vtVUq9n//nJgEwB25UFk
> debug1: load_hostkeys: fopen /Users/ishan/.ssh/known_hosts2: No such file or directory
> debug1: load_hostkeys: fopen /opt/homebrew/etc/ssh/ssh_known_hosts: No such file or directory
> debug1: load_hostkeys: fopen /opt/homebrew/etc/ssh/ssh_known_hosts2: No such file or directory
> debug1: Host 'devzat.hackclub.com' is known and matches the RSA host key.
> debug1: Found key in /Users/ishan/.ssh/known_hosts:1
> debug1: rekey out after 134217728 blocks
> debug1: SSH2_MSG_NEWKEYS sent
> debug1: expecting SSH2_MSG_NEWKEYS
> debug1: SSH2_MSG_NEWKEYS received
> debug1: rekey in after 134217728 blocks
> debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
> debug1: Will attempt key: /Users/ishan/.ssh/id_rsa RSA SHA256:/30Vhs3sufvZ/NTJVIUiSTwpFyvDEh10bIOyiZO9cj4
> debug1: Will attempt key: /Users/ishan/.ssh/id_ecdsa
> debug1: Will attempt key: /Users/ishan/.ssh/id_ecdsa_sk
> debug1: Will attempt key: /Users/ishan/.ssh/id_ed25519
> debug1: Will attempt key: /Users/ishan/.ssh/id_ed25519_sk
> debug1: Will attempt key: /Users/ishan/.ssh/id_xmss
> debug1: Will attempt key: /Users/ishan/.ssh/id_dsa
> debug1: SSH2_MSG_SERVICE_ACCEPT received
> debug1: Authentications that can continue: publickey
> debug1: Next authentication method: publickey
> debug1: Offering public key: /Users/ishan/.ssh/id_rsa RSA SHA256:/30Vhs3sufvZ/NTJVIUiSTwpFyvDEh10bIOyiZO9cj4
> debug1: send_pubkey_test: no mutual signature algorithm
> debug1: Trying private key: /Users/ishan/.ssh/id_ecdsa
> debug1: Trying private key: /Users/ishan/.ssh/id_ecdsa_sk
> debug1: Trying private key: /Users/ishan/.ssh/id_ed25519
> debug1: Trying private key: /Users/ishan/.ssh/id_ed25519_sk
> debug1: Trying private key: /Users/ishan/.ssh/id_xmss
> debug1: Trying private key: /Users/ishan/.ssh/id_dsa
> debug1: No more authentication methods to try.
> ishan@devzat.hackclub.com: Permission denied (publickey).
```

**Comment by quackduck** [comment] 2022-05-03 16:59
Okay nvm that was a bit premature; I tested the fix wrong.

**Comment by quackduck** [comment] 2022-05-22 13:39
OKAY ACTUALLY FIXED NOW IN https://github.com/quackduck/devzat/commit/93dfd63d7b39932a7e269808a108efce21466928 🎉

**Closed by quackduck** 2022-05-22 13:39 UTC
Labels: bug

**Comment by Arkaeriit** [comment] 2022-05-23 06:04
Yay!
